# -*- coding: utf-8 -*-
"""109.11.09 自訂函式.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-S3nMwD1PUhG4dQrXVax93NixA595Xr
"""

def SayHello():
  print('歡迎光臨!')

#建立名稱為GetAera()的函式,width(寬)*height(高)
def GetArea(width, height):
  area = width * height
  return area
#建立函式後並不會自動執行,需在主程式中直接用函式名稱加上()，視需求加上參數,即可呼叫
area = GetArea(6,9) #54

#輸入攝氏溫度，求華氏溫度
def ctof(c):
  f = c * 1.8 + 32
  return f

inputc = float(input("請輸入攝氏溫度: "))
print("華氏溫度為: %3.1f 度" % ctof(inputc))

#設定參數預設值，方法為[參數=值]

def GetArea(width, height=12):
  area = width * height
  return area
area1 = GetArea(6) #72
area2 = GetArea(6, 9) #54

#預設的參數必須置於參數串列最後，否則執行會產生錯誤
def GetArea(width, height=12): #正確
def GetArea(width=6, height): #錯誤，需移至後方

#建立不定數目參數函式
def add(n1, n2):
  return n1 + n2
#多數值加法器
def calsum(*params):
  total = 0
  for param in params:
    total += param
  return total

print('不定數目範例')
print('2個參數:calsum(4,5) = %d' % calsum(4,5))
print('3個參數:calsum(4,5,12) = %d' % calsum(4,5,12))
print('4個參數:calsum(4,5,12,8) = %d' % calsum(4,5,12,8))

#函數中變數有效範圍
#全域變數:定義在函式外的變數，有效範圍是整個PY檔案
#區域變數:定義在一個函式中的變數，有效範圍是在該函式内
def scope():
  var1 = 1 #區域變數
  return var1, var2
var1 = 10 #全域變數
var2 = 20 #全域變數
x, y = scope()
print(x, y) #1 20
print(var1, var2) #10 20

#如果要在函式內使用全域變數，需在函式中以global宣告
def scope():
  global var1 #宣告全域變數
  var1 = 1
  return var1, var2
var1 = 10 #全域變數
var2 = 20 #全域變數
x, y = scope()
print(x, y) #1 20
print(var1, var2) #1 20

#pow(x,y,z),為x的y次方除以z的餘數
pow(3, 4, 7) #4 

#round(x, y),y是設定小數位數(省略為整數),4捨6入5成雙
round(3.76, 1) #3.8
round(3.74, 1) #3.7
round(3.75, 1) #3.8
round(3.65, 1) #3.6

#sorted()是預設由小排到大，若是以reverse=True,做為第2個參數，會由大到小排序
sorted([3,1,7,5], reverse=True) #[7, 5, 3, 1]

#內建函式應用
innum = 0
list1 = []
while(innum != -1):
  innum = int(input('請輸入正整數(-1:結束):'))
  list1.append(innum)
list1.pop()
print('共輸入 %d 個數' % len(list1))
print('最大數為: %d' % max(list1))
print('最小數為: %d' % min(list1))
print('輸入數的總合為: %d' % sum(list1))
print('輸入數由大到小排序為:{}'.format(sorted(list1, reverse=True)))