# -*- coding: utf-8 -*-
"""109.11.04 Dict()字典.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LDQBwfCnkvSjmhWwnjYODlF-wPC4KOmY
"""

#與串列類似，其元素是以(鍵-值)對方是儲存，就可使用鍵來取得值。
dict1 = {'香蕉':20,'蘋果':50,'橘子':30}
print(dict1['蘋果']) #50

#如果鍵值重複的話，前面的鍵值會被覆蓋，只有最後面的鍵有效
dict2 = {'香蕉':20,'蘋果':50,'橘子':30, '香蕉':25}
print(dict2['香蕉']) #25

#元素在字典中的排列順序是隨機的，與設定順序不一定相同
dict1 = {'香蕉':20,'蘋果':50,'橘子':30,'柚子':15}
print(dict1[20]) #錯誤，不能以索引取值
print(dict1['鳳梨']) #錯誤，鍵值不存在

#修改元素值:方法是對鍵設定新的值，新的元素會取代舊元素值
dict = {'香蕉':20,'蘋果':50,'橘子':30,'柚子':15}
dict['香蕉'] =222
print(['香蕉'])

#新增元素值:設定新鍵及新值
dict = {'香蕉':20,'蘋果':50,'橘子':30,'柚子':15}
dict['芭樂'] = 17
print(dict)

#刪除字典元素
dict1 = {'香蕉':20,'蘋果':50,'橘子':30,'柚子':15}
del dict1['蘋果'] #刪除字典中特定元素
dict1.clear() #刪除字典所有元素，但保留字典
del  dict1  #直接刪除字典，之後字典不存在

#進階字典操作
dict = {'joe':5,'mary':8}
len(dict) #取得元素個數,2
dict.clear() #移除所有元素,空值
dict.copy #複製字典,{'joe':5,'mary':8}
dict.items() #取得以[鍵-值]為元素的組合
dict.keys() #取得以[鍵]為元素的組合
dict.values() #取得以[值]為元素組合
dict.get(鍵,值) #取得[鍵]對應的值，若鍵不存在就傳回參數的值
dict.setdefault(鍵,值) #若[鍵]不存在就以參數的[鍵-值]建立新元素

#keys()資料型態為dict_keys
#values()資料型態為dict_values
#items()資料型態為dict_items
#可將keys()和values()取得的資料以list()函式轉換為串列，轉成串列才能取得元素值，將兩者組合就可以列印字典全部內容

#顯示字典內容
dict1={"王小名":85, "曾山水":93, "鄭美麗":67}
dict1['黃小姐'] = 71
dict1['陳莉莉'] = 98
listkey = list(dict1.keys())
listvalue = list(dict1.values())
for n in range(len(listkey)):
  print("%s 的成績為 %d 分" % (listkey[n], listvalue[n]))

#顯示字典內容-items
dict1={"王小名":85, "曾山水":93, "鄭美麗":67}
dict1['黃小姐'] = 71
dict1['陳莉莉'] = 98
listitem = dict1.items()
for name, score in listitem:
  print("%s 的成績為 %d 分" % (name, score))

#get() 字典名稱.get(鍵, 預設值)
dict1 = {"香蕉":20, "蘋果":50, "橘子":30}
n=dict1.get("蘋果") #n=50
n=dict1.get("蘋果", 100) #n=50 #鍵存在,傳回值
n=dict1.get("鳳梨") #n=None
n=dict1.get("鳳梨", 100) #n=100 #傳回預設值

#setdefault() #額外設定的鍵值會加入字典中
dict1 = {"香蕉":20, "蘋果":50, "橘子":30}
n=dict1.setdefault("蘋果") #n=50,dict1未改變
n=dict1.setdefault("蘋果", 100) #n=50,dict1未改變

n=dict1.setdefault("鳳梨") #n=None,會加入字典中
,dict1 = {"香蕉":20, "蘋果":50, "橘子":30, "鳳梨":None}

n=dict1.setdefault("鳳梨":100) #n=100,會加入字典中
,dict1 = {"香蕉":20, "蘋果":50, "橘子":30, "鳳梨":100}