# -*- coding: utf-8 -*-
"""109.11.04 if...eles雙向判斷式.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTwXSVThMlnVJBIoKFDTPV8p2VqeLFdr
"""

#if...eles雙向判斷式

pw = input("請輸入密碼:")
if pw=="1234":
	print("歡迎光臨!")
else:
	print("密碼錯誤!")