# -*- coding: utf-8 -*-
"""109.11.04 Tuple元組.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19LCDmAdQgPp128JZXxHksgEHhJnzF_TS
"""

#元組讀結構與串列完全相同，不同處在於元素個數及元素值皆不能改變
tuple1 = (1,2,3,4,5)
tuple2 = (1,'香蕉', True)
tuple3 = ('香蕉', '蘋果', '橘子')
print(tuple3[1])
tuple3[1] = '芭樂' #錯誤，元素值不能修改
#因為不能改變元素值，所以append、insert不能使用
tuple4 = (1,2,3,4,5)
n = len(tuple4) #n=5
tuple4.append(8) #錯誤，不能增加元素值

"""元組的優點:
  1.執行速度比串列快
  2.儲存元組的資料較為安全
"""