# -*- coding: utf-8 -*-
"""109.11.18 os模組.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lNsO0ukmTfI1Q706_DoqY3-k78kmAVwI
"""

#getcwd() 可以取得目前的工作目錄
import os
print(os.getcwd())

#remove() 刪除指定的檔案，一般會配合os.path的exists()，先檢查該檔案是否存在，再決定是否刪除檔案。
import os
gile = 'myFile.txt'
if os.path.exists(file):
  os.remove
else:
  print(file + '檔案未建立!')

#mkdir()函式 可以建立指定的目錄
import os
dir = 'myDir'
if not os.path.exists(dir):
  os.mkdir(dir)
else:
  print(dir + '已經建立!')

#rmdir() 可以刪除指定的目錄
import os
dir = 'myDir'
if os.path.exists(dir):
  os.rmdir(dir)
else:
  print(dir + '目錄未建立!')

#system() 執行作業系統命令
import os
cur_path=os.path.dirname(__file__) #取得目前路徑
os.system('cls') #清除螢幕
os.system('mkdir dir2') #建立dir2目錄
os.system('copy sssystem.py dir2\copyfile.py') #複製檔案
file=cur_path + '\dir2\copyfile.py'
os.system('notepad' + file) #以記事本開啟copyfile.py檔

#os.path模組 處理檔案路徑和名稱，檢查檔案或路徑是否存在

#需使用IPython console執行

import os.path
cur_path=os.path.dirname(__name__) #取得目前目錄路徑
print('現在目錄路徑:'+cur_path)

filename=os.name.abspath('ospath.py')
if os.path.exists(filename):
  print('完整路徑名稱:'+filename)
  print('檔案大小:', os.path.getsize(filename))

basename=os.path.basename(filename)
print('最後的檔案或路徑名稱:' + basename)

dirname=os.path.dirname(filename)
print('目前檔案目錄名稱:' + dirname)

print('是否為目錄:',os.pathisdir(filename))

fullpath,fname=os.path.split(filename)
print('目錄路徑:' + fullpath)
print('檔名:' + fname)

Drive,fpath=os.path.splitdrive(filename)
print('磁碟機:' + Drive)
print('路徑名稱:' + fpath)

fullpath = os.pathjoin(fullpath + '\\' + fname)
print('組合路徑=' + fullpath)

#os.walk() 可以搜尋指定目錄及以及其子目錄，會回傳一個包含3個元素的元組:資料夾名稱、下一層資料夾串列、資料夾中所有檔案創串列。

#需使用IPython console執行
import os
cur_path=os.path.dirname(__file__) #取得目前路徑
sample_tree=os.walk(cur_path)
for dirname,subdir,files in sameple_tree:
  print('檔案路徑L' dirname)
  print('目錄串列:', subdir)
  print('檔案串列:', files)
  print()

#shutil 模組 可跨平台的檔案處理模組，首先必須匯入shutil
#需使用IPython console執行
#複製shutil.py為shutil.py
import os,shutil
cur_path=os.path.dirname(__file__) #取得目前路徑
destfile= cur_path + '\\' + 'newfile.py'
shutil.copy(shutil.py,destfile) #檔案複製

#glob模組 取得指定條件的檔案串列
#需使用IPython console執行
import glob
files = glob.glob('glob.py') +glob.glob('os*.py') +glob.glob('*.txt')
for file in files:
  print(file)

#open() 共有8個參數，第一個檔案名稱不可省略