# -*- coding: utf-8 -*-
"""109.11.04 for迴圈.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NB7aH5hacpjj7O3-6MfBL0zYxJb7s3G2
"""

# for 變數 in 串列:(換行Tab)程式區塊

list1 = ["香蕉","蘋果","橘子"]
for s in list1:
	print(s, end=",") #執行結果為 : 香蕉,蘋果,橘子,