# -*- coding: utf-8 -*-
"""109.11.04 if...elif...else多向判斷式.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P_5HV9O1VuUwZpuYz294EOLtqD_6CV-o
"""

score = input("請輸入成績:")
if(int(score) >=90):
	print("優等")
elif(int(score) >=80):
	print("甲等")
elif(int(score) >=70):
	print("乙等")
elif(int(score) >=60):
	print("丙等")
else:
	print("丁等")